<?php
/**
 * EbayFulfillmentProgramTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Ebay\Sell\Fulfillment
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.19.7
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ebay\Sell\Fulfillment\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EbayFulfillmentProgramTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to provide details about an order line item being fulfilled by eBay or an eBay fulfillment partner.
 * @package     Ebay\Sell\Fulfillment
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EbayFulfillmentProgramTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EbayFulfillmentProgram"
     */
    public function testEbayFulfillmentProgram()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fulfilled_by"
     */
    public function testPropertyFulfilledBy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
